---
# This is the main file for the insights demo deployment section
# This createsthe inventory and deploys the hosts.

- name: Create the ansible inventory for testing Insights
  hosts: localhost
  connection: local
  vars_files:
  - vars/hostlist.yml
  - vars/vaultvars.yml
 
  tasks:
  - name: Create the inventory to be used for insights demos
    ansible.controller.inventory:
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      name:  "{{ inventory_name }}"
      description: "{{ inventory_description }}"
      organization: "{{ inventory_organization }}"
      state: present
      
  - name: Create the host entries in the inventory
    ansible.controller.host:
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      name: "{{ host.name }}"
      description: "{{ host.description }}"
      inventory: "{{ inventory_name }}"
      state: present
      variables: "{{ host.variables }}"
    loop: "{{ inventory_hosts }}"
    loop_control:
      loop_var: host

  


  