---
# This play creates the demo content views defined in vars/contentviews.yml
- name: Create the demo content views
  hosts: all
  vars_files: 
  - vars/contentviews.yml
  - ../AutomatingContentManagement/group_vars/all/vault_all.yml

  tasks:
  - ansible.builtin.import_role:
      name: ../AutomatingContentManagement/roles/cvcreator
  - ansible.builtin.import_role:
      name: ../AutomatingContentManagement/roles/ccvcreator
  - ansible.builtin.import_role:
      name: ../AutomatingContentManagement/roles/cvpublisher
  - ansible.builtin.import_role:
      name: ../AutomatingContentManagement/roles/cvpromoter
