---
controller_host: "https://tower.parmstrong.ca"
controller_username: "{{ vault_controller_username }}"
controller_password: "{{ vault_controller_password }}"
inventoryname: "InsightsDemoInventory"
inventoryhosts:
- name: "insightsjboss.parmstrong.ca"
  description: "a test jboss standalone host for testing with insights"
  variables:
    fqdn: "insightsjboss.parmstrong.ca"
    hostgroup: "InsightsDemo/ID_JBoss"
    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.4"
    compute_resource: "vcenter.parmstrong.ca"
    compute_profile: "2-Medium"
    mac: "00:50:56:ff:ff:ff"
    dhostname: ""
- name: "insightsrhel7.parmstrong.ca"
  description: "a test RHEL7 server for demonstrating Red Hat Insights"
  variables:
    fqdn: "insightsrhel7.parmstrong.ca"
    hostgroup: "InsightsDemo/ID_RHEL7"
    kickstart_repository: "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9"
    compute_resource: "vcenter.parmstrong.ca"
    compute_profile: "2-Medium"
    mac: "00:50:56:ff:ff:ff"
    dhostname: ""
- name: "insightsrhel8.parmstrong.ca"
  description: "a test RHEL 8 server for demonstrating Red Hat Insights"
  variables:
    fqdn: "insightsrhel8.parmstrong.ca"
    hostgroup: "InsightsDemo/ID_RHEL8"
    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.4"
    compute_resource: "vcenter.parmstrong.ca"
    compute_profile: "2-Medium"
    mac: "00:50:56:ff:ff:ff"
    dhostname: ""
